/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a0.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a0.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a30.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a30.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a60.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a60.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a90.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a90.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a120.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a120.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a150.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a150.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a180.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a180.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a210.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a210.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a240.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a240.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a270.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a270.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a300.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a300.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s0_a330.mci > /home/nicolas/CUDAMCFL/MCIs/s0_a330.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a0.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a0.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a30.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a30.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a60.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a60.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a90.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a90.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a120.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a120.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a150.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a150.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a180.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a180.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a210.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a210.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a240.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a240.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a270.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a270.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a300.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a300.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s1_a330.mci > /home/nicolas/CUDAMCFL/MCIs/s1_a330.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a0.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a0.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a30.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a30.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a60.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a60.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a90.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a90.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a120.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a120.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a150.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a150.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a180.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a180.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a210.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a210.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a240.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a240.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a270.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a270.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a300.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a300.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s2_a330.mci > /home/nicolas/CUDAMCFL/MCIs/s2_a330.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a0.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a0.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a30.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a30.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a60.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a60.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a90.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a90.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a120.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a120.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a150.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a150.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a180.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a180.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a210.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a210.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a240.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a240.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a270.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a270.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a300.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a300.mci.log
/home/nicolas/CUDAMCFL/cuda_fl /home/nicolas/CUDAMCFL/MCIs//home/nicolas/CUDAMCFL/MCIs/s3_a330.mci > /home/nicolas/CUDAMCFL/MCIs/s3_a330.mci.log
